<img src="https://mfalonso.pythonanywhere.com/static/img/Sklearn1.png" width=400 height=400 align="center">
# SKLEARN Overview
## Your Machine Learning buddy



<img src="https://mfalonso.pythonanywhere.com/static/img/profile_manoelgadi.png" width=100 height=100 align="right">

Author: Prof. Manoel Gadi

Contact: mfalonso@faculty.ie.edu

Teaching Web: http://mfalonso.pythonanywhere.com

Last revision: 26/Sept/2020

### Pros:

- Convenient - All-In-One Library - the Swiss Knife of Machine Learning in Python
<img src="https://mfalonso.pythonanywhere.com/static/img/Sklearn2_swiss_army_knife.jpg" width=100 height=100 align="right">
- Resilient
- Community driven and good help

### Cons:

- Black boxes
- Debugging
- Backward compatibility


<img src="https://mfalonso.pythonanywhere.com/static/img/Sklearn3_background.png" width=800 height=800 align="center">

### Before going any further, let' play with Scikit-Learn once first!

Create a Python code for a logistic regression of sklearn using the variables Pclass, Sex and Embarked from the Titanic dataset directly from an internet source or GitHub, transform the variables into dummy variables. Set the seed so that all variables always get the same value. Split the data into training and testing. Print the classification report of the model.

In [128]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

# Load the Titanic dataset
url = 'https://raw.githubusercontent.com/manoelgadi/PSDMA/refs/heads/main/datasets/titanic_data.csv'
titanic_data = pd.read_csv(url)

# Transform categorical variables into dummy variables
titanic_data = pd.get_dummies(titanic_data, columns=['Pclass', 'Sex', 'Embarked'], drop_first=True)

# Define the features and target variable
X = titanic_data[['Pclass_2', 'Pclass_3', 'Sex_male', 'Embarked_Q', 'Embarked_S']]
y = titanic_data['Survived']

# Set the seed for reproducibility
np.random.seed(42)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Create and fit the logistic regression model
model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)

# Predict on the test set
y_pred = model.predict(X_test)

# Print the classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      0.85      0.83       157
           1       0.77      0.70      0.74       111

    accuracy                           0.79       268
   macro avg       0.79      0.78      0.78       268
weighted avg       0.79      0.79      0.79       268

Exercise:
1) Print the classification report for the train data. What can be concluded?

# Excercise:
2. Adapt the previous code in order to apply the following 5 classification models:

* from sklearn.linear_model import LogisticRegression
* from sklearn.tree import DecisionTreeClassifier
* from sklearn.svm import SVC
* from sklearn.neighbors import KNeighborsClassifier
* from sklearn.ensemble import RandomForestClassifier

### Which model seems better?

# Doing a development:

In [129]:
#General
import pandas as pd
import numpy as np

df = pd.read_excel("https://github.com/manoelgadi/PSDMA/raw/refs/heads/main/datasets/yahoo.xlsx")
target = "Beta"
df = df.fillna(0)

In [130]:
df

,Unnamed: 0,ticker,country,sector,RefIndex,Market Cap,Enterprise Value,Trailing P/E,Forward P/E,PEG Ratio,...,Trailing Annual Dividend Rate,Trailing Annual Dividend Yield,5 Year Average Dividend Yield,Payout Ratio,Dividend Date,Ex-Dividend Date,Last Split Factor,Last Split Date,ScrapedName,Sector
0,0,GOOG,USA,Technology,SPY,818.1B,712.95B,50.67,24.460000,1.700000,...,0.000000,0,0.000000,0.00%,0,0,10000000/10000000,"Apr 27, 2015",Alphabet Inc. (GOOG),Technology
1,1,MSFT,USA,Technology,SPY,879.31B,830.01B,53.84,23.260000,2.140000,...,1.680000,1.47%,2.350000,77.46%,"Dec 13, 2018","Nov 14, 2018",2/1,"Feb 18, 2003",Microsoft Corporation (MSFT),Technology
2,2,FB,USA,Technology,SPY,477.58B,428.23B,25.59,19.860000,1.020000,...,0.000000,0,0.000000,0.00%,0,0,0,0,"Facebook, Inc. (FB)",Technology
3,3,T,USA,Technology,SPY,246.25B,424.67B,6.63,9.320000,1.560000,...,1.990000,5.89%,5.250000,38.79%,"Aug 1, 2018","Jul 9, 2018",2/1,"Mar 20, 1998",AT&amp;T Inc. (T),Communication Services
4,4,ORCL,USA,Technology,SPY,203.99B,192.27B,56.93,14.040000,1.790000,...,0.760000,1.49%,1.360000,78.35%,"Oct 30, 2018","Oct 15, 2018",2/1,"Oct 13, 2000",Oracle Corporation (ORCL),Technology
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,81,ABT,USA,Healthcare,SPY,125.33B,138.97B,136.86,22.120000,2.010000,...,1.110000,1.60%,2.070000,236.96%,"Nov 15, 2018","Oct 12, 2018",10000/4798,"Jan 2, 2013",Abbott Laboratories (ABT),Healthcare
82,82,NVO,USA,Healthcare,SPY,115.45B,113.53B,19.22,18.590000,2.330000,...,1.230000,2.57%,2.140000,49.05%,"Aug 28, 2018","Aug 17, 2018",5/1,"Jan 9, 2014",Novo Nordisk A/S (NVO),Healthcare
83,83,CVS,USA,Healthcare,SPY,80.16B,102.23B,26.81,10.760000,0.990000,...,2.000000,2.51%,1.840000,68.49%,"Aug 1, 2018","Jul 24, 2018",2/1,"Jun 7, 2005",CVS Health Corporation (CVS),Healthcare
84,84,AZN,USA,Healthcare,SPY,93.29B,112.44B,35.88,20.130000,1.790000,...,2.800000,7.43%,4.310000,132.70%,"Sep 10, 2018","Aug 9, 2018",2/1,"Jul 27, 2015",Astrazeneca PLC (AZN),Healthcare
85,85,TMO,USA,Healthcare,SPY,97.54B,116.73B,40.90,19.780000,1.850000,...,0.640000,0.26%,0.420000,10.80%,"Oct 15, 2018","Sep 14, 2018",3/2,"Jun 6, 1996",Thermo Fisher Scientific Inc (TMO),Healthcare

### a quick helper code for you: a trick to get only columns with certain types

In [131]:
def get_specific_columns(df, data_types, to_ignore = list(), ignore_target = False):
    columns = df.select_dtypes(include=data_types).columns
    if ignore_target:
        columns = filter(lambda x: x not in to_ignore, list(columns))
    return columns

In [132]:
help(filter)

Help on class filter in module builtins:

class filter(object)
 |  filter(function or None, iterable) --> filter object
 |
 |  Return an iterator yielding those items of iterable for which function(item)
 |  is true. If function is None, return the items that are true.
 |
 |  Methods defined here:
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __iter__(self, /)
 |      Implement iter(self).
 |
 |  __next__(self, /)
 |      Implement next(self).
 |
 |  __reduce__(...)
 |      Return state information for pickling.
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  __new__(*args, **kwargs)
 |      Create and return a new object.  See help(type) for accurate signature.

In [133]:
list(filter(lambda x: x>2, [1,2,3,4]))

[3, 4]

In [134]:
list(filter(lambda x: x not in ['Beta'], df.columns))

['Unnamed: 0',
 'ticker',
 'country',
 'sector',
 'RefIndex',
 'Market Cap',
 'Enterprise Value',
 'Trailing P/E',
 'Forward P/E',
 'PEG Ratio',
 'Price/Sales',
 'Price/Book',
 'Enterprise Value/Revenue',
 'Enterprise Value/EBITDA',
 'Fiscal Year Ends',
 'Most Recent Quarter',
 'Profit Margin',
 'Operating Margin',
 'Return on Assets',
 'Return on Equity',
 'Revenue',
 'Revenue Per Share',
 'Quarterly Revenue Growth',
 'Gross Profit',
 'EBITDA',
 'Net Income Avi to Common',
 'Diluted EPS',
 'Quarterly Earnings Growth',
 'Total Cash',
 'Total Cash Per Share',
 'Total Debt',
 'Total Debt/Equity',
 'Current Ratio',
 'Book Value Per Share',
 'Operating Cash Flow',
 'Levered Free Cash Flow',
 '52-Week Change',
 'S&amp;P500 52-Week Change',
 '52 Week High',
 '52 Week Low',
 '50-Day Moving Average',
 '200-Day Moving Average',
 'Avg Vol (3 month)',
 'Avg Vol (10 day)',
 'Shares Outstanding',
 'Float',
 '% Held by Insiders',
 '% Held by Institutions',
 'Shares Short',
 'Short Ratio',
 'Short % of Float',
 'Shares Short (prior month )',
 'Forward Annual Dividend Rate',
 'Forward Annual Dividend Yield',
 'Trailing Annual Dividend Rate',
 'Trailing Annual Dividend Yield',
 '5 Year Average Dividend Yield',
 'Payout Ratio',
 'Dividend Date',
 'Ex-Dividend Date',
 'Last Split Factor',
 'Last Split Date',
 'ScrapedName',
 'Sector']

---

In [135]:
variables = get_specific_columns(df, ["float64", "int64"], [target], ignore_target = True)

In [136]:
print(list(variables))

['Unnamed: 0', 'Forward P/E', 'PEG Ratio', 'Price/Sales', 'Price/Book', 'Enterprise Value/Revenue', 'Enterprise Value/EBITDA', 'Diluted EPS', 'Current Ratio', '52 Week Low', 'Short Ratio', 'Shares Short (prior month )', 'Forward Annual Dividend Rate', 'Trailing Annual Dividend Rate', '5 Year Average Dividend Yield']

In [137]:
print(type(variables))

<class 'filter'>

### 1.2 Quick and dirty model with Scikit-Learn

In [138]:
X = df[list(get_specific_columns(df, ["float64", "int64"], [target], ignore_target = True))]
target = "Beta"
y = df[target]

In [139]:
print("X=",X,"y=",y)

X=     Unnamed: 0  Forward P/E  PEG Ratio  Price/Sales  Price/Book  \
0            0    24.460000   1.700000     6.600000    5.040000
1            1    23.260000   2.140000     7.970000   10.640000
2            2    19.860000   1.020000     9.850000    6.020000
3            3     9.320000   1.560000     1.550000    1.350000
4            4    14.040000   1.790000     5.110000    4.480000
..         ...          ...        ...          ...         ...
81          81    22.120000   2.010000     4.240000    4.100000
82          82    18.590000   2.330000     6.780000   15.170000
83          83    10.760000   0.990000     0.430000    2.250000
84          84    20.130000   1.790000     4.180000    7.590000
85          85    19.780000   1.850000     4.220000    3.690000

    Enterprise Value/Revenue  Enterprise Value/EBITDA  Diluted EPS  \
0                   5.750000                18.660000    23.160000
1                   7.520000                18.460000     2.130000
2                   8.830000                15.630000     6.460000
3                   2.680000                 9.340000     5.120000
4                   4.820000                11.900000     0.900000
..                       ...                      ...          ...
81                  4.700000                20.320000     0.520000
82                  6.670000                14.640000     2.500000
83                  0.550000                 8.020000     2.940000
84                  5.030000                25.120000     1.050000
85                  5.050000                20.190000     5.920000

    Current Ratio  52 Week Low  Short Ratio  Shares Short (prior month )  \
0        4.150000   921.140000     1.630000                     0.000000
1        2.900000    72.990000     2.080000                     0.000000
2       10.670000   149.020000     1.030000                     0.000000
3        0.810000    30.130000     2.670000                     0.000000
4        3.420000    42.570000     3.570000                     0.000000
..            ...          ...          ...                          ...
81       1.580000    51.550000     3.050000                     0.000000
82       1.170000    44.280000     2.130000                     0.000000
83       2.340000    60.140000     7.600000                     0.000000
84       0.720000    31.990000     2.410000                     0.000000
85       1.580000   181.510000     3.390000                     0.000000

    Forward Annual Dividend Rate  Trailing Annual Dividend Rate  \
0                       0.000000                       0.000000
1                       1.840000                       1.680000
2                       0.000000                       0.000000
3                       2.000000                       1.990000
4                       0.760000                       0.760000
..                           ...                            ...
81                      1.120000                       1.110000
82                      1.270000                       1.230000
83                      2.000000                       2.000000
84                      1.400000                       2.800000
85                      0.680000                       0.640000

    5 Year Average Dividend Yield
0                        0.000000
1                        2.350000
2                        0.000000
3                        5.250000
4                        1.360000
..                            ...
81                       2.070000
82                       2.140000
83                       1.840000
84                       4.310000
85                       0.420000

[86 rows x 15 columns] y= 0    1.400000
1    1.260000
2    0.660000
3    0.370000
4    1.110000
       ...
81   1.740000
82   0.820000
83   0.940000
84   0.500000
85   1.330000
Name: Beta, Length: 86, dtype: float64

Predicting the target * Beta * with a Random Forest Regressor

In [140]:
dir()

['GridSearchCV',
 'In',
 'LabelEncoder',
 'LogisticRegression',
 'MinMaxScaler',
 'Out',
 'RandomForestRegressor',
 'StandardScaler',
 'X',
 'X_cleaned',
 'X_test',
 'X_train',
 '_',
 '_100',
 '_102',
 '_113',
 '_115',
 '_116',
 '_117',
 '_118',
 '_121',
 '_13',
 '_130',
 '_133',
 '_134',
 '_16',
 '_17',
 '_23',
 '_25',
 '_27',
 '_28',
 '_29',
 '_31',
 '_32',
 '_34',
 '_36',
 '_43',
 '_46',
 '_47',
 '_53',
 '_55',
 '_57',
 '_58',
 '_59',
 '_6',
 '_61',
 '_62',
 '_64',
 '_66',
 '_7',
 '_79',
 '_82',
 '_83',
 '_89',
 '_91',
 '_93',
 '_94',
 '_95',
 '_97',
 '_98',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i100',
 '_i101',
 '_i102',
 '_i103',
 '_i104',
 '_i105',
 '_i106',
 '_i107',
 '_i108',
 '_i109',
 '_i11',
 '_i110',
 '_i111',
 '_i112',
 '_i113',
 '_i114',
 '_i115',
 '_i116',
 '_i117',
 '_i118',
 '_i119',
 '_i12',
 '_i120',
 '_i121',
 '_i122',
 '_i123',
 '_i124',
 '_i125',
 '_i126',
 '_i127',
 '_i128',
 '_i129',
 '_i13',
 '_i130',
 '_i131',
 '_i132',
 '_i133',
 '_i134',
 '_i135',
 '_i136',
 '_i137',
 '_i138',
 '_i139',
 '_i14',
 '_i140',
 '_i15',
 '_i16',
 '_i17',
 '_i18',
 '_i19',
 '_i2',
 '_i20',
 '_i21',
 '_i22',
 '_i23',
 '_i24',
 '_i25',
 '_i26',
 '_i27',
 '_i28',
 '_i29',
 '_i3',
 '_i30',
 '_i31',
 '_i32',
 '_i33',
 '_i34',
 '_i35',
 '_i36',
 '_i37',
 '_i38',
 '_i39',
 '_i4',
 '_i40',
 '_i41',
 '_i42',
 '_i43',
 '_i44',
 '_i45',
 '_i46',
 '_i47',
 '_i48',
 '_i49',
 '_i5',
 '_i50',
 '_i51',
 '_i52',
 '_i53',
 '_i54',
 '_i55',
 '_i56',
 '_i57',
 '_i58',
 '_i59',
 '_i6',
 '_i60',
 '_i61',
 '_i62',
 '_i63',
 '_i64',
 '_i65',
 '_i66',
 '_i67',
 '_i68',
 '_i69',
 '_i7',
 '_i70',
 '_i71',
 '_i72',
 '_i73',
 '_i74',
 '_i75',
 '_i76',
 '_i77',
 '_i78',
 '_i79',
 '_i8',
 '_i80',
 '_i81',
 '_i82',
 '_i83',
 '_i84',
 '_i85',
 '_i86',
 '_i87',
 '_i88',
 '_i89',
 '_i9',
 '_i90',
 '_i91',
 '_i92',
 '_i93',
 '_i94',
 '_i95',
 '_i96',
 '_i97',
 '_i98',
 '_i99',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'actual_RFR_model',
 'classification_report',
 'cross_val_score',
 'cross_valer',
 'df',
 'df_cleaned',
 'df_feature_importance',
 'df_importance',
 'df_test',
 'df_train',
 'exit',
 'fitted_model',
 'get_ipython',
 'get_specific_columns',
 'grid',
 'grid_search',
 'label_encoded',
 'label_encoder',
 'list_of_20best_variables',
 'model',
 'model_blueprint_RFR',
 'np',
 'optimal_model',
 'pd',
 'quit',
 'results',
 'scaler',
 'splitter',
 'target',
 'titanic_data',
 'train_test_split',
 'url',
 'v',
 'variables',
 'y',
 'y_cleaned',
 'y_pred',
 'y_test',
 'y_train']

In [141]:
from sklearn.ensemble import RandomForestRegressor

In [142]:
dir()

['GridSearchCV',
 'In',
 'LabelEncoder',
 'LogisticRegression',
 'MinMaxScaler',
 'Out',
 'RandomForestRegressor',
 'StandardScaler',
 'X',
 'X_cleaned',
 'X_test',
 'X_train',
 '_',
 '_100',
 '_102',
 '_113',
 '_115',
 '_116',
 '_117',
 '_118',
 '_121',
 '_13',
 '_130',
 '_133',
 '_134',
 '_140',
 '_16',
 '_17',
 '_23',
 '_25',
 '_27',
 '_28',
 '_29',
 '_31',
 '_32',
 '_34',
 '_36',
 '_43',
 '_46',
 '_47',
 '_53',
 '_55',
 '_57',
 '_58',
 '_59',
 '_6',
 '_61',
 '_62',
 '_64',
 '_66',
 '_7',
 '_79',
 '_82',
 '_83',
 '_89',
 '_91',
 '_93',
 '_94',
 '_95',
 '_97',
 '_98',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i100',
 '_i101',
 '_i102',
 '_i103',
 '_i104',
 '_i105',
 '_i106',
 '_i107',
 '_i108',
 '_i109',
 '_i11',
 '_i110',
 '_i111',
 '_i112',
 '_i113',
 '_i114',
 '_i115',
 '_i116',
 '_i117',
 '_i118',
 '_i119',
 '_i12',
 '_i120',
 '_i121',
 '_i122',
 '_i123',
 '_i124',
 '_i125',
 '_i126',
 '_i127',
 '_i128',
 '_i129',
 '_i13',
 '_i130',
 '_i131',
 '_i132',
 '_i133',
 '_i134',
 '_i135',
 '_i136',
 '_i137',
 '_i138',
 '_i139',
 '_i14',
 '_i140',
 '_i141',
 '_i142',
 '_i15',
 '_i16',
 '_i17',
 '_i18',
 '_i19',
 '_i2',
 '_i20',
 '_i21',
 '_i22',
 '_i23',
 '_i24',
 '_i25',
 '_i26',
 '_i27',
 '_i28',
 '_i29',
 '_i3',
 '_i30',
 '_i31',
 '_i32',
 '_i33',
 '_i34',
 '_i35',
 '_i36',
 '_i37',
 '_i38',
 '_i39',
 '_i4',
 '_i40',
 '_i41',
 '_i42',
 '_i43',
 '_i44',
 '_i45',
 '_i46',
 '_i47',
 '_i48',
 '_i49',
 '_i5',
 '_i50',
 '_i51',
 '_i52',
 '_i53',
 '_i54',
 '_i55',
 '_i56',
 '_i57',
 '_i58',
 '_i59',
 '_i6',
 '_i60',
 '_i61',
 '_i62',
 '_i63',
 '_i64',
 '_i65',
 '_i66',
 '_i67',
 '_i68',
 '_i69',
 '_i7',
 '_i70',
 '_i71',
 '_i72',
 '_i73',
 '_i74',
 '_i75',
 '_i76',
 '_i77',
 '_i78',
 '_i79',
 '_i8',
 '_i80',
 '_i81',
 '_i82',
 '_i83',
 '_i84',
 '_i85',
 '_i86',
 '_i87',
 '_i88',
 '_i89',
 '_i9',
 '_i90',
 '_i91',
 '_i92',
 '_i93',
 '_i94',
 '_i95',
 '_i96',
 '_i97',
 '_i98',
 '_i99',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'actual_RFR_model',
 'classification_report',
 'cross_val_score',
 'cross_valer',
 'df',
 'df_cleaned',
 'df_feature_importance',
 'df_importance',
 'df_test',
 'df_train',
 'exit',
 'fitted_model',
 'get_ipython',
 'get_specific_columns',
 'grid',
 'grid_search',
 'label_encoded',
 'label_encoder',
 'list_of_20best_variables',
 'model',
 'model_blueprint_RFR',
 'np',
 'optimal_model',
 'pd',
 'quit',
 'results',
 'scaler',
 'splitter',
 'target',
 'titanic_data',
 'train_test_split',
 'url',
 'v',
 'variables',
 'y',
 'y_cleaned',
 'y_pred',
 'y_test',
 'y_train']

In [143]:
model_blueprint_RFR = RandomForestRegressor(n_estimators=50, random_state=42)

In [144]:
model_blueprint_RFR.fit(X,y)

RandomForestRegressor(n_estimators=50, random_state=42)

In [145]:
model_blueprint_RFR.predict(X)

array([1.3698, 1.1952, 0.9348, 0.4952, 1.1132, 0.7432, 0.9256, 0.9874,
       1.1172, 0.8766, 1.6002, 0.9508, 1.1042, 0.7044, 1.3588, 0.9202,
       1.5912, 1.128 , 0.426 , 0.664 , 0.5716, 0.6718, 0.7404, 0.682 ,
       0.7364, 1.7664, 0.5468, 0.8972, 0.6224, 0.5972, 1.0972, 1.4722,
       0.5674, 1.5004, 0.4354, 1.1606, 1.1276, 1.015 , 0.6876, 1.0408,
       0.6434, 0.7794, 0.4694, 1.2672, 1.0356, 1.3712, 0.7766, 1.3252,
       0.8314, 1.303 , 1.0916, 1.163 , 1.196 , 1.4036, 1.0176, 0.8104,
       1.4916, 1.0272, 0.9468, 0.8398, 1.0586, 1.4134, 1.3712, 1.3032,
       1.3616, 1.4372, 1.1908, 1.082 , 0.9024, 0.8938, 0.8826, 0.875 ,
       0.996 , 1.4304, 0.8336, 1.2726, 1.3312, 0.7166, 1.3602, 1.024 ,
       0.678 , 1.468 , 0.856 , 1.1182, 0.6088, 1.2952])

In [146]:
model_blueprint_RFR

RandomForestRegressor(n_estimators=50, random_state=42)

In [147]:
actual_RFR_model = model_blueprint_RFR.fit(X, y)

In [148]:
model_blueprint_RFR.predict(X)

array([1.3698, 1.1952, 0.9348, 0.4952, 1.1132, 0.7432, 0.9256, 0.9874,
       1.1172, 0.8766, 1.6002, 0.9508, 1.1042, 0.7044, 1.3588, 0.9202,
       1.5912, 1.128 , 0.426 , 0.664 , 0.5716, 0.6718, 0.7404, 0.682 ,
       0.7364, 1.7664, 0.5468, 0.8972, 0.6224, 0.5972, 1.0972, 1.4722,
       0.5674, 1.5004, 0.4354, 1.1606, 1.1276, 1.015 , 0.6876, 1.0408,
       0.6434, 0.7794, 0.4694, 1.2672, 1.0356, 1.3712, 0.7766, 1.3252,
       0.8314, 1.303 , 1.0916, 1.163 , 1.196 , 1.4036, 1.0176, 0.8104,
       1.4916, 1.0272, 0.9468, 0.8398, 1.0586, 1.4134, 1.3712, 1.3032,
       1.3616, 1.4372, 1.1908, 1.082 , 0.9024, 0.8938, 0.8826, 0.875 ,
       0.996 , 1.4304, 0.8336, 1.2726, 1.3312, 0.7166, 1.3602, 1.024 ,
       0.678 , 1.468 , 0.856 , 1.1182, 0.6088, 1.2952])

In [149]:
actual_RFR_model

RandomForestRegressor(n_estimators=50, random_state=42)

In [150]:
# RandomForestRegressor(n_estimators=50, random_state=42).fit(X, y).predict(X)

In [151]:
model_blueprint_RFR

RandomForestRegressor(n_estimators=50, random_state=42)

In [152]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=50, random_state=42) # Blueprint - carbon copy
model.fit(X, y)
y_pred = model.predict(X)

In [153]:
y_pred

array([1.3698, 1.1952, 0.9348, 0.4952, 1.1132, 0.7432, 0.9256, 0.9874,
       1.1172, 0.8766, 1.6002, 0.9508, 1.1042, 0.7044, 1.3588, 0.9202,
       1.5912, 1.128 , 0.426 , 0.664 , 0.5716, 0.6718, 0.7404, 0.682 ,
       0.7364, 1.7664, 0.5468, 0.8972, 0.6224, 0.5972, 1.0972, 1.4722,
       0.5674, 1.5004, 0.4354, 1.1606, 1.1276, 1.015 , 0.6876, 1.0408,
       0.6434, 0.7794, 0.4694, 1.2672, 1.0356, 1.3712, 0.7766, 1.3252,
       0.8314, 1.303 , 1.0916, 1.163 , 1.196 , 1.4036, 1.0176, 0.8104,
       1.4916, 1.0272, 0.9468, 0.8398, 1.0586, 1.4134, 1.3712, 1.3032,
       1.3616, 1.4372, 1.1908, 1.082 , 0.9024, 0.8938, 0.8826, 0.875 ,
       0.996 , 1.4304, 0.8336, 1.2726, 1.3312, 0.7166, 1.3602, 1.024 ,
       0.678 , 1.468 , 0.856 , 1.1182, 0.6088, 1.2952])

Assigning the prediction back to the original dataframe

In [154]:
df['Beta_predicted1'] = y_pred

Now that we have done our job, let's export the data with our prediction back to csv

In [155]:
df.to_excel("yahoo_clean_predicted1.xlsx")

In [156]:
df.to_csv("yahoo_clean_data.csv")

In [157]:
df = pd.read_csv("yahoo_clean_data.csv")

# Why using slow (non-typed) csv format? If we can use binary typed Hadoop File System?

Remember that comunication between CPU/Memory and Input/Output is text-only.
<img src="https://mfalonso.pythonanywhere.com/static/img/Computer_system_bus.png" width=400 height=400 align="center">

In [158]:
df.to_hdf("yahoo_clean_data.h5", 'df')

/tmp/ipython-input-4158798923.py:1: FutureWarning: Starting with pandas version 3.0 all arguments of to_hdf except for the argument 'path_or_buf' will be keyword-only.
  df.to_hdf("yahoo_clean_data.h5", 'df')

If we had another dataframe called __df1__, we could place it into the same Hadoop file

In [159]:
# df1.to_hdf("clean_data.h5", 'df1')

If we had another dataframe called __df2__, we could place it into the same Hadoop file

In [160]:
# df2.to_hdf("clean_data.h5", 'df2')

Then to read the dataframe __df__ back from file into memory, we simply do:

In [161]:
df = pd.read_hdf("yahoo_clean_data.h5",'df')

# Is this the best Scikit-Learn can do? Of course not...

<img src="https://mfalonso.pythonanywhere.com/static/img/Slide3.png" width=800 height=800 align="center">

<img src="https://mfalonso.pythonanywhere.com/static/img/Slide5.png" width=800 height=800 align="center">

<img src="https://mfalonso.pythonanywhere.com/static/img/Slide6.png" width=800 height=800 align="center">

<img src="https://mfalonso.pythonanywhere.com/static/img/Slide7.png" width=800 height=800 align="center">

<img src="https://mfalonso.pythonanywhere.com/static/img/Slide8.png" width=800 height=800 align="center">

<img src="https://mfalonso.pythonanywhere.com/static/img/Slide9.png" width=800 height=800 align="center">

<img src="https://mfalonso.pythonanywhere.com/static/img/Slide10.png" width=800 height=800 align="center">

<img src="https://mfalonso.pythonanywhere.com/static/img/Slide20.png" width=800 height=800 align="center">

### Processing/Cleaning - Standard Scaler

http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html
- Standardize features by removing the mean and scaling to unit variance

In [162]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
"-----------------------"
import pandas as pd
df = pd.read_excel("https://github.com/manoelgadi/PSDMA/raw/refs/heads/main/datasets/yahoo.xlsx")

variables = get_specific_columns(df, ["float64", "int64"], [target], ignore_target = True)
for v in variables:
    print(v, "- before scaling: mean= {:.10f}".format(df[v].values.mean()), " - min: {:.10f}".format(df[v].values.min()), " - max: {:.10f}".format(df[v].values.max()))
    df[v] = scaler.fit_transform(df[[v]])
    print(v, "- after scaling: mean= {:.10f}".format(df[v].values.mean()), " - min: {:.10f}".format(df[v].values.min()), " - max: {:.10f}".format(df[v].values.max()))
    print("-"*50)

Unnamed: 0 - before scaling: mean= 42.5000000000  - min: 0.0000000000  - max: 85.0000000000
Unnamed: 0 - after scaling: mean= -0.0000000000  - min: -1.7120264258  - max: 1.7120264258
--------------------------------------------------
Forward P/E - before scaling: mean= nan  - min: nan  - max: nan
Forward P/E - after scaling: mean= nan  - min: nan  - max: nan
--------------------------------------------------
PEG Ratio - before scaling: mean= nan  - min: nan  - max: nan
PEG Ratio - after scaling: mean= nan  - min: nan  - max: nan
--------------------------------------------------
Price/Sales - before scaling: mean= nan  - min: nan  - max: nan
Price/Sales - after scaling: mean= nan  - min: nan  - max: nan
--------------------------------------------------
Price/Book - before scaling: mean= nan  - min: nan  - max: nan
Price/Book - after scaling: mean= nan  - min: nan  - max: nan
--------------------------------------------------
Enterprise Value/Revenue - before scaling: mean= nan  - min: nan  - max: nan
Enterprise Value/Revenue - after scaling: mean= nan  - min: nan  - max: nan
--------------------------------------------------
Enterprise Value/EBITDA - before scaling: mean= nan  - min: nan  - max: nan
Enterprise Value/EBITDA - after scaling: mean= nan  - min: nan  - max: nan
--------------------------------------------------
Diluted EPS - before scaling: mean= nan  - min: nan  - max: nan
Diluted EPS - after scaling: mean= nan  - min: nan  - max: nan
--------------------------------------------------
Current Ratio - before scaling: mean= nan  - min: nan  - max: nan
Current Ratio - after scaling: mean= nan  - min: nan  - max: nan
--------------------------------------------------
52 Week Low - before scaling: mean= nan  - min: nan  - max: nan
52 Week Low - after scaling: mean= nan  - min: nan  - max: nan
--------------------------------------------------
Short Ratio - before scaling: mean= nan  - min: nan  - max: nan
Short Ratio - after scaling: mean= nan  - min: nan  - max: nan
--------------------------------------------------
Shares Short (prior month ) - before scaling: mean= nan  - min: nan  - max: nan
Shares Short (prior month ) - after scaling: mean= nan  - min: nan  - max: nan
--------------------------------------------------
Forward Annual Dividend Rate - before scaling: mean= nan  - min: nan  - max: nan
Forward Annual Dividend Rate - after scaling: mean= nan  - min: nan  - max: nan
--------------------------------------------------
Trailing Annual Dividend Rate - before scaling: mean= nan  - min: nan  - max: nan
Trailing Annual Dividend Rate - after scaling: mean= nan  - min: nan  - max: nan
--------------------------------------------------
5 Year Average Dividend Yield - before scaling: mean= nan  - min: nan  - max: nan
5 Year Average Dividend Yield - after scaling: mean= nan  - min: nan  - max: nan
--------------------------------------------------

/usr/local/lib/python3.12/dist-packages/sklearn/utils/extmath.py:1101: RuntimeWarning: invalid value encountered in divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
/usr/local/lib/python3.12/dist-packages/sklearn/utils/extmath.py:1106: RuntimeWarning: invalid value encountered in divide
  T = new_sum / new_sample_count
/usr/local/lib/python3.12/dist-packages/sklearn/utils/extmath.py:1126: RuntimeWarning: invalid value encountered in divide
  new_unnormalized_variance -= correction**2 / new_sample_count

### Processing - MinMaxScaler

http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html#sklearn.preprocessing.MinMaxScaler
- This estimator scales and translates each feature individually such that it is in the given range on the training set, i.e. between zero and one.

In [163]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
"-----------------------"
import pandas as pd
df = pd.read_excel("https://github.com/manoelgadi/PSDMA/raw/refs/heads/main/datasets/yahoo.xlsx")

variables = get_specific_columns(df, ["float64", "int64"], [target], ignore_target = True)
for v in variables:
    print(v, "- before scaling: mean= {:.10f}".format(df[v].values.mean()), " - min: {:.10f}".format(df[v].values.min()), " - max: {:.10f}".format(df[v].values.max()))
    df[v] = scaler.fit_transform(df[[v]])
    print(v, "- after scaling: mean= {:.10f}".format(df[v].values.mean()), " - min: {:.10f}".format(df[v].values.min()), " - max: {:.10f}".format(df[v].values.max()))
    print("-"*50)

Unnamed: 0 - before scaling: mean= 42.5000000000  - min: 0.0000000000  - max: 85.0000000000
Unnamed: 0 - after scaling: mean= 0.5000000000  - min: 0.0000000000  - max: 1.0000000000
--------------------------------------------------
Forward P/E - before scaling: mean= nan  - min: nan  - max: nan
Forward P/E - after scaling: mean= nan  - min: nan  - max: nan
--------------------------------------------------
PEG Ratio - before scaling: mean= nan  - min: nan  - max: nan
PEG Ratio - after scaling: mean= nan  - min: nan  - max: nan
--------------------------------------------------
Price/Sales - before scaling: mean= nan  - min: nan  - max: nan
Price/Sales - after scaling: mean= nan  - min: nan  - max: nan
--------------------------------------------------
Price/Book - before scaling: mean= nan  - min: nan  - max: nan
Price/Book - after scaling: mean= nan  - min: nan  - max: nan
--------------------------------------------------
Enterprise Value/Revenue - before scaling: mean= nan  - min: nan  - max: nan
Enterprise Value/Revenue - after scaling: mean= nan  - min: nan  - max: nan
--------------------------------------------------
Enterprise Value/EBITDA - before scaling: mean= nan  - min: nan  - max: nan
Enterprise Value/EBITDA - after scaling: mean= nan  - min: nan  - max: nan
--------------------------------------------------
Diluted EPS - before scaling: mean= nan  - min: nan  - max: nan
Diluted EPS - after scaling: mean= nan  - min: nan  - max: nan
--------------------------------------------------
Current Ratio - before scaling: mean= nan  - min: nan  - max: nan
Current Ratio - after scaling: mean= nan  - min: nan  - max: nan
--------------------------------------------------
52 Week Low - before scaling: mean= nan  - min: nan  - max: nan
52 Week Low - after scaling: mean= nan  - min: nan  - max: nan
--------------------------------------------------
Short Ratio - before scaling: mean= nan  - min: nan  - max: nan
Short Ratio - after scaling: mean= nan  - min: nan  - max: nan
--------------------------------------------------
Shares Short (prior month ) - before scaling: mean= nan  - min: nan  - max: nan
Shares Short (prior month ) - after scaling: mean= nan  - min: nan  - max: nan
--------------------------------------------------
Forward Annual Dividend Rate - before scaling: mean= nan  - min: nan  - max: nan
Forward Annual Dividend Rate - after scaling: mean= nan  - min: nan  - max: nan
--------------------------------------------------
Trailing Annual Dividend Rate - before scaling: mean= nan  - min: nan  - max: nan
Trailing Annual Dividend Rate - after scaling: mean= nan  - min: nan  - max: nan
--------------------------------------------------
5 Year Average Dividend Yield - before scaling: mean= nan  - min: nan  - max: nan
5 Year Average Dividend Yield - after scaling: mean= nan  - min: nan  - max: nan
--------------------------------------------------

/usr/local/lib/python3.12/dist-packages/sklearn/utils/_array_api.py:776: RuntimeWarning: All-NaN slice encountered
  return xp.asarray(numpy.nanmin(X, axis=axis))
/usr/local/lib/python3.12/dist-packages/sklearn/utils/_array_api.py:793: RuntimeWarning: All-NaN slice encountered
  return xp.asarray(numpy.nanmax(X, axis=axis))

### Processing - Enconding - Dummy Creation with Pandas Get Dummies

https://pandas.pydata.org/pandas-docs/stable/generated/pandas.get_dummies.html

Convert categorical variable into dummy/indicator variables

In [164]:
pd.get_dummies(df.sector)

    Consumer  Financial  Healthcare  Services  Technology
0      False      False       False     False        True
1      False      False       False     False        True
2      False      False       False     False        True
3      False      False       False     False        True
4      False      False       False     False        True
..       ...        ...         ...       ...         ...
81     False      False        True     False       False
82     False      False        True     False       False
83     False      False        True     False       False
84     False      False        True     False       False
85     False      False        True     False       False

[86 rows x 5 columns]

Adding dummy columns to the original dataframe

In [165]:
df = pd.concat([df, pd.get_dummies(df['sector'])], axis=1);
print(df)

    Unnamed: 0 ticker country      sector RefIndex Market Cap  \
0     0.000000   GOOG     USA  Technology      SPY     818.1B
1     0.011765   MSFT     USA  Technology      SPY    879.31B
2     0.023529     FB     USA  Technology      SPY    477.58B
3     0.035294      T     USA  Technology      SPY    246.25B
4     0.047059   ORCL     USA  Technology      SPY    203.99B
..         ...    ...     ...         ...      ...        ...
81    0.952941    ABT     USA  Healthcare      SPY    125.33B
82    0.964706    NVO     USA  Healthcare      SPY    115.45B
83    0.976471    CVS     USA  Healthcare      SPY     80.16B
84    0.988235    AZN     USA  Healthcare      SPY     93.29B
85    1.000000    TMO     USA  Healthcare      SPY     97.54B

   Enterprise Value Trailing P/E  Forward P/E  PEG Ratio  ...  \
0           712.95B        50.67     0.188635   0.066667  ...
1           830.01B        53.84     0.176459   0.074489  ...
2           428.23B        25.59     0.141958   0.054578  ...
3           424.67B         6.63     0.035008   0.064178  ...
4           192.27B        56.93     0.082902   0.068267  ...
..              ...          ...          ...        ...  ...
81          138.97B       136.86     0.164891   0.072178  ...
82          113.53B        19.22     0.129072   0.077867  ...
83          102.23B        26.81     0.049619   0.054044  ...
84          112.44B        35.88     0.144698   0.068267  ...
85          116.73B        40.90     0.141147   0.069333  ...

    Ex-Dividend Date  Last Split Factor  Last Split Date  \
0                NaN  10000000/10000000     Apr 27, 2015
1       Nov 14, 2018                2/1     Feb 18, 2003
2                NaN                NaN              NaN
3        Jul 9, 2018                2/1     Mar 20, 1998
4       Oct 15, 2018                2/1     Oct 13, 2000
..               ...                ...              ...
81      Oct 12, 2018         10000/4798      Jan 2, 2013
82      Aug 17, 2018                5/1      Jan 9, 2014
83      Jul 24, 2018                2/1      Jun 7, 2005
84       Aug 9, 2018                2/1     Jul 27, 2015
85      Sep 14, 2018                3/2      Jun 6, 1996

                            ScrapedName                  Sector Consumer  \
0                  Alphabet Inc. (GOOG)              Technology    False
1          Microsoft Corporation (MSFT)              Technology    False
2                   Facebook, Inc. (FB)              Technology    False
3                     AT&amp;T Inc. (T)  Communication Services    False
4             Oracle Corporation (ORCL)              Technology    False
..                                  ...                     ...      ...
81            Abbott Laboratories (ABT)              Healthcare    False
82               Novo Nordisk A/S (NVO)              Healthcare    False
83         CVS Health Corporation (CVS)              Healthcare    False
84                Astrazeneca PLC (AZN)              Healthcare    False
85   Thermo Fisher Scientific Inc (TMO)              Healthcare    False

   Financial Healthcare Services Technology
0      False      False    False       True
1      False      False    False       True
2      False      False    False       True
3      False      False    False       True
4      False      False    False       True
..       ...        ...      ...        ...
81     False       True    False      False
82     False       True    False      False
83     False       True    False      False
84     False       True    False      False
85     False       True    False      False

[86 rows x 70 columns]

### Processing - Enconding - Category Creation with Preprocessing LabelEncoder

http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html

Encode labels with value between 0 and n_classes-1.

In [166]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
label_encoded = label_encoder.fit_transform(df['sector'])
label_encoded

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Adding groups to the original dataframe is piece of cake!

In [167]:
df['sector_label_encoded'] = label_encoded
df[['sector', 'sector_label_encoded']]

        sector  sector_label_encoded
0   Technology                     4
1   Technology                     4
2   Technology                     4
3   Technology                     4
4   Technology                     4
..         ...                   ...
81  Healthcare                     2
82  Healthcare                     2
83  Healthcare                     2
84  Healthcare                     2
85  Healthcare                     2

[86 rows x 2 columns]

### Side note - very cool and handy use of LabelEncoder - to anonymise datasets!

In [168]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
label_encoded = label_encoder.fit_transform(df['ticker'])
df['ticker_label_encoded'] = label_encoded
df[['ticker', 'ticker_label_encoded']]

   ticker  ticker_label_encoded
0    GOOG                    31
1    MSFT                    53
2      FB                    26
3       T                    68
4    ORCL                    59
..    ...                   ...
81    ABT                     2
82    NVO                    57
83    CVS                    23
84    AZN                     8
85    TMO                    70

[86 rows x 2 columns]

### Feature Selection - just a matter of combining things, I am using the trainning sample not the whole sample

In [169]:
"Sklearn"
"-----------------------"

from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
fitted_model = model.fit(X, y)
"-----------------------"

df_feature_importance = pd.DataFrame(
    {'FeatureName': X.columns, 'FeatureImportance': model.feature_importances_ })

pd.options.display.float_format = '{:,.6f}'.format
df_feature_importance.sort_values(by=['FeatureImportance'], ascending=False)

                      FeatureName  FeatureImportance
14  5 Year Average Dividend Yield           0.142110
8                   Current Ratio           0.109522
9                     52 Week Low           0.088844
2                       PEG Ratio           0.086191
10                    Short Ratio           0.081606
7                     Diluted EPS           0.076127
0                      Unnamed: 0           0.075816
1                     Forward P/E           0.072969
4                      Price/Book           0.070256
3                     Price/Sales           0.057302
12   Forward Annual Dividend Rate           0.049002
6         Enterprise Value/EBITDA           0.030734
5        Enterprise Value/Revenue           0.029994
13  Trailing Annual Dividend Rate           0.029526
11    Shares Short (prior month )           0.000000

In [170]:
df_importance = df_feature_importance.sort_values(by=['FeatureImportance'], ascending=False)

In [171]:
list_of_20best_variables = list(df_importance['FeatureName'][0:20])

In [172]:
model.fit(X[list_of_20best_variables],y).predict(X[list_of_20best_variables])

array([1.3212, 1.1788, 0.9574, 0.5741, 1.1589, 0.7389, 0.9061, 0.9717,
       1.1614, 0.9419, 1.6222, 0.9507, 1.1233, 0.8086, 1.3173, 0.9312,
       1.5535, 1.1747, 0.4227, 0.6833, 0.5265, 0.6886, 0.7382, 0.6424,
       0.804 , 1.7514, 0.5789, 0.8595, 0.6875, 0.5624, 1.0095, 1.4057,
       0.6068, 1.5221, 0.4819, 1.1858, 1.1127, 1.0146, 0.6887, 1.0345,
       0.7596, 0.7896, 0.4975, 1.2436, 0.9952, 1.3998, 0.8129, 1.2937,
       0.9135, 1.271 , 0.9318, 1.1919, 1.1897, 1.5607, 1.0376, 0.8721,
       1.4509, 1.0703, 0.9932, 0.8929, 1.0428, 1.3872, 1.3256, 1.3954,
       1.3596, 1.5016, 1.1936, 0.9827, 0.8196, 0.9192, 0.9063, 0.8713,
       0.9793, 1.3666, 0.8562, 1.2795, 1.3156, 0.7626, 1.362 , 1.0196,
       0.688 , 1.4741, 0.8654, 1.0857, 0.6652, 1.2883])

### Train-Test Split

In [173]:
"Sklearn"
"-----------------------"
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
splitter = train_test_split
"-----------------------"

df_train, df_test = splitter(df, test_size = 0.2, random_state = 42)
print("Dataset shape: {shape}".format(shape = df_train.shape))
print("Dataset shape: {shape}".format(shape = df_test.shape))

Dataset shape: (68, 72)
Dataset shape: (18, 72)

Now that we have the sample, we must create again our X and y with that sample.

In [174]:
variables = list(get_specific_columns(df, ["float64", "int64"], [target], ignore_target = True))
target = "Beta"

X_train= df_train[variables]
y_train = df_train[target]

X_test= df_test[variables]
y_test = df_test[target]

### Cross-Validation - One can replace train and test split by cross validation

http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html

Evaluate a score by cross-validation

In [175]:
"Sklearn"
"-----------------------"
from sklearn.model_selection import cross_val_score
cross_valer = cross_val_score
"-----------------------"

results = cross_valer(model, X, y, cv = 30)
print("Cross Validation Scores: {results}".format(results = results))

Cross Validation Scores: [-9.37723684e-01 -8.89744898e-03 -5.47717896e-01 -1.10564574e-01
 -2.89595208e-01 -5.34241134e-01 -3.59484062e-01 -1.55419781e+02
 -8.39176905e-02 -9.73853111e+01  1.27173501e-01  3.12644068e-01
  7.05630145e-01 -2.15019417e+00 -1.94598219e+00 -5.53838702e-01
 -1.69417817e+00 -3.13927773e+00  5.02978655e-01 -4.54380357e-01
  6.02166597e-01 -2.07964867e+01 -2.51873048e+00 -1.41717416e+01
  6.85811390e-02 -4.16862559e-01 -1.62373049e+00 -1.30196536e-01
 -2.71426889e+01  6.94237190e-01]

### Hyper Parameter Optimization - Grid Search Fine Tuning

In [176]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
import numpy as np

grid = {
    "n_estimators": [10, 50],
    # 'auto' is no longer a valid option for max_features in newer sklearn versions
    "max_features": ['sqrt', 'log2'],
    "bootstrap": [True, False],
    "random_state": [42]
}

"Sklearn"
"-----------------------"

# Drop rows with NaN values in the target variable before splitting
df_cleaned = df.dropna(subset=[target])
X_cleaned = df_cleaned[variables]
y_cleaned = df_cleaned[target]

# Split the cleaned data
df_train, df_test = splitter(df_cleaned, test_size = 0.2, random_state = 42)
X_train= df_train[variables]
y_train = df_train[target]
X_test= df_test[variables]
y_test = df_test[target]

grid_search = GridSearchCV(RandomForestRegressor(), param_grid = grid, cv = 3)
grid_search.fit(X_train, y_train)
optimal_model = grid_search.best_estimator_
"-----------------------"

print("Fine Tuned Model: {0}".format(optimal_model))

Fine Tuned Model: RandomForestRegressor(max_features='sqrt', n_estimators=50, random_state=42)

### Training the model using the optimized parameters IMPLICITLY

In [177]:
"Sklearn"
"-----------------------"
fitted_model = optimal_model.fit(X_train, y_train)

#Predicting on the training data
print(fitted_model.predict(X_train))

[1.3834 1.1482 0.9234 0.9368 0.888  0.9744 0.7342 0.962  1.5328 0.7128
 0.7754 1.4342 0.4294 1.3716 1.2198 1.5528 1.204  1.077  0.8964 1.0052
 0.7902 0.957  1.796  0.9626 0.7536 1.349  0.535  1.1154 0.7572 1.1634
 0.6958 0.9504 1.1004 0.7684 1.408  1.1764 1.3472 0.6098 0.9248 0.8254
 0.7098 0.8558 0.5724 1.2456 0.8324 0.9824 0.7952 1.2744 0.9698 0.5886
 1.398  1.0356 1.4088 0.8796 0.9886 0.6672 1.1656 1.5094 0.6718 0.846
 0.6574 0.5758 1.3744 0.5688 1.4184 0.994  1.3418 1.2226]

In [178]:
#Predicting on the test data
print(fitted_model.predict(X_test))

[0.8778 1.1062 0.8218 0.7408 0.9804 1.3592 1.0264 0.6564 1.1712 1.4016
 0.898  1.2972 1.1158 1.0432 1.412  1.2188 1.0454]

In [179]:
optimal_model

RandomForestRegressor(max_features='sqrt', n_estimators=50, random_state=42)

### Training the model using the optimized parameters EXPLICITLY

In [180]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=50, random_state=42)
fitted_model = model.fit(X_train, y_train)
#Predicting on the training data
print("Predicting on the training data",fitted_model.predict(X_train))

#Predicting on the test data
print("Predicting on the test data", fitted_model.predict(X_test))

Predicting on the training data [1.3764 1.1    1.0378 0.9508 1.0048 1.0044 0.7398 0.896  1.4864 0.7508
 0.8236 1.3342 0.4532 1.3452 1.275  1.5564 1.2786 1.0754 0.8464 1.0518
 0.7534 1.0112 1.7602 0.9944 0.8178 1.3754 0.545  1.118  0.6812 1.1344
 0.868  1.01   1.0866 0.6554 1.4288 1.2134 1.3534 0.5558 0.8942 0.8634
 0.7536 0.9268 0.5394 1.2972 0.837  0.9924 0.7866 1.2884 0.9332 0.5532
 1.4432 1.0206 1.4328 0.7848 1.0898 0.6254 1.1692 1.5062 0.6594 0.8218
 0.6618 0.6044 1.2872 0.587  1.437  0.8968 1.4812 1.2316]
Predicting on the test data [0.767  1.0066 0.817  0.7494 1.122  1.3642 0.9862 0.6174 1.292  1.445
 0.815  1.267  1.1662 1.1386 1.391  1.2648 1.0338]

### Assessing the model

http://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_squared_error.html

Mean squared error regression loss

In [181]:
"Sklearn"
"-----------------------"
from sklearn.metrics import mean_squared_error
predictions = model.predict(X_test)
actuals = y_test
"-----------------------"

RMSE = mean_squared_error(predictions, actuals)
print("RMSE Error: {0}".format(RMSE))

RMSE Error: 0.19357497882352945

In [182]:
#model.fit(X).mean_squared_error(actual)

### with Classification

In [183]:
df_train[target+'_class'] = df_train[target].apply(lambda x: 1 if x > df_train[target].values.mean() else 0)
y_train_class = df_train[target+'_class']
df_test[target+'_class'] = df_test[target].apply(lambda x: 1 if x > df_test[target].values.mean() else 0)
y_test_class = df_test[target+'_class']

In [184]:
df_train[[target,target+'_class']]

       Beta  Beta_class
78 1.420000           1
43 1.300000           1
50 0.840000           0
11 0.950000           0
30 0.780000           0
..      ...         ...
20 0.480000           0
61 1.460000           1
72 1.060000           1
14 1.600000           1
52 1.310000           1

[68 rows x 2 columns]

In [185]:
"Sklearn"
"-----------------------"
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
fitted_model = model.fit(X_train, y_train_class)

predictions = fitted_model.predict(X_test)
actuals = y_test_class
"-----------------------"


print("Accuracy: {0}".format(sum(predictions == actuals) /len(predictions)))

Accuracy: 0.7647058823529411

In [186]:
"Sklearn"
"-----------------------"
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(predictions, actuals)
"-----------------------"

print("True Positives: {0}".format(confusion[0][0]))
print("False Positives: {0}".format(confusion[0][1]))
print("False Negatives: {0}".format(confusion[1][0]))
print("True Negatives: {0}".format(confusion[1][1]))

confusion

True Positives: 5
False Positives: 1
False Negatives: 3
True Negatives: 8

array([[5, 1],
       [3, 8]])

<img src="https://mfalonso.pythonanywhere.com/static/img/Slide13.png" width=800 height=800 align="center">

<img src="https://mfalonso.pythonanywhere.com/static/img/05_BestPracticesInMachineLearningWithGlassOfComputerScientist.jpg" width=800 height=800 align="center">

# Scikit Learn is a library or a framework?

So, in simple terms: library is Numpy, where import it to do some matrix multiplication.

And framework dictate how your project will be structured. How should I write my code.

    If we use the metaphor of architecture, libraries are bricks, and frameworks are, fittingly, the frame.

<img src="https://mfalonso.pythonanywhere.com/static/img/library_or_framework.png" width=600 height=600 align="center">

Source:  https://medium.com/datafire-io/libraries-vs-frameworks-626cdde799a7